<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InitSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('animal_especies')
            ->insert($this->animal_especies());

        DB::table('animal_families')
            ->insert($this->animal_families());

        DB::table('animals')
            ->insert($this->animals());
    }

    private function animal_especies(): array
    {
        return [
            [
                'name' => 'Cachorro',
                'description' => 'Também chamado de cão, é um mamífero carnívoro da família dos canídeos, subespécie do lobo, e talvez o mais antigo animal domesticado pelo ser humano.',
                'status' => 1,
            ],
            [
                'name' => 'Gato',
                'description' => 'Gato é um mamífero carnívoro da família dos felídeos, muito popular como animal de estimação. Ocupando o topo da cadeia alimentar, é predador natural de diversos animais, como roedores, pássaros, lagartixas e alguns insetos.',
                'status' => 1,
            ],
            [
                'name' => 'Cavalo',
                'description' => 'O cavalo é uma das duas subespécies existentes de Equus ferus. É um mamífero perissodáctilo pertencente à família taxonômica Equidae. O cavalo evoluiu há entre 45 milhões a 55 milhões de anos, desde uma pequena criatura com vários dedos, o Eohippus, até o animal grande e com um único dedo de hoje.',
                'status' => 1,
            ],
        ];
    }

    private function animal_families(): array
    {
        return [
            [
                'name' => 'Canídeos',
                'description' => ' Os canídeos têm uma cauda longa e dentes molares adaptados para esmagar ossos.',
                'time_exploration' => 20,
                'status' => 1,
            ],
            [
                'name' => 'Felídeos',
                'description' => 'Felídeos são uma família de animais mamíferos digitígrados, da ordem dos carnívoros.',
                'time_exploration' => 10,
                'status' => 1,
            ],
            [
                'name' => 'Equidae',
                'description' => 'Os equinos constituem uma família de mamíferos perissodáctilos. Esta família abarca apenas o género Equus, onde se classificam o cavalo e o burro, além da zebra.',
                'time_exploration' => 30,
                'status' => 1,
            ],
            [
                'name' => 'Suidae',
                'description' => 'Suidae é uma família de mamíferos artiodáctilos. Esta família taxonómica inclui vários géneros, nos quais se encontram espécies de animais domésticos, como o porco-doméstico, e selvagens tais como o javali, o facocero e o babirussa.',
                'time_exploration' => 15,
                'status' => 1,
            ],
        ];
    }

    private function animals(): array
    {
        return [
            [
                'animal_especie_id' => 1,
                'animal_family_id' => 1,
                'name' => 'Cachorro',
                'description' => 'Cachorro',
                'min_hp' => 1,
                'max_hp' => 10,
                'min_attack' => 1,
                'max_attack' => 10,
                'min_defense' => 1,
                'max_defense' => 10,
                'image_path' => 'uploads/animals/cachorro.png',
            ],
            [
                'animal_especie_id' => 1,
                'animal_family_id' => 1,
                'name' => 'Buddy',
                'description' => 'Cachorro',
                'min_hp' => 150,
                'max_hp' => 300,
                'min_attack' => 50,
                'max_attack' => 200,
                'min_defense' => 100,
                'max_defense' => 250,
                'image_path' => 'uploads/animals/cachorro-2.png',
            ],
            [
                'animal_especie_id' => 1,
                'animal_family_id' => 1,
                'name' => 'Bella',
                'description' => 'Cachorro',
                'min_hp' => 200,
                'max_hp' => 400,
                'min_attack' => 75,
                'max_attack' => 250,
                'min_defense' => 125,
                'max_defense' => 300,
                'image_path' => 'uploads/animals/cachorro-3.png',
            ],
            [
                'animal_especie_id' => 1,
                'animal_family_id' => 1,
                'name' => 'Charlie',
                'description' => 'Cachorro',
                'min_hp' => 250,
                'max_hp' => 500,
                'min_attack' => 100,
                'max_attack' => 300,
                'min_defense' => 150,
                'max_defense' => 350,
                'image_path' => 'uploads/animals/cachorro-4.png',
            ],
            [
                'animal_especie_id' => 1,
                'animal_family_id' => 1,
                'name' => 'Luna',
                'description' => 'Cachorro',
                'min_hp' => 300,
                'max_hp' => 600,
                'min_attack' => 125,
                'max_attack' => 350,
                'min_defense' => 175,
                'max_defense' => 400,
                'image_path' => 'uploads/animals/cachorro-5.png',
            ],
            [
                'animal_especie_id' => 1,
                'animal_family_id' => 1,
                'name' => 'Max',
                'description' => 'Cachorro',
                'min_hp' => 350,
                'max_hp' => 700,
                'min_attack' => 150,
                'max_attack' => 400,
                'min_defense' => 200,
                'max_defense' => 450,
                'image_path' => 'uploads/animals/cachorro-6.png',
            ],
            [
                'animal_especie_id' => 1,
                'animal_family_id' => 1,
                'name' => 'Lucy',
                'description' => 'Cachorro',
                'min_hp' => 400,
                'max_hp' => 800,
                'min_attack' => 175,
                'max_attack' => 450,
                'min_defense' => 225,
                'max_defense' => 500,
                'image_path' => 'uploads/animals/cachorro-7.png',
            ],
            [
                'animal_especie_id' => 1,
                'animal_family_id' => 1,
                'name' => 'Cooper',
                'description' => 'Cachorro',
                'min_hp' => 450,
                'max_hp' => 900,
                'min_attack' => 200,
                'max_attack' => 500,
                'min_defense' => 250,
                'max_defense' => 550,
                'image_path' => 'uploads/animals/cachorro-8.png',
            ],
            [
                'animal_especie_id' => 1,
                'animal_family_id' => 1,
                'name' => 'Daisy',
                'description' => 'Cachorro',
                'min_hp' => 500,
                'max_hp' => 1000,
                'min_attack' => 225,
                'max_attack' => 550,
                'min_defense' => 275,
                'max_defense' => 600,
                'image_path' => 'uploads/animals/cachorro-9.png',
            ],
            [
                'animal_especie_id' => 1,
                'animal_family_id' => 1,
                'name' => 'Bailey',
                'description' => 'Cachorro',
                'min_hp' => 550,
                'max_hp' => 1000,
                'min_attack' => 250,
                'max_attack' => 600,
                'min_defense' => 300,
                'max_defense' => 650,
                'image_path' => 'uploads/animals/cachorro.png',
            ],
            [
                'animal_especie_id' => 2,
                'animal_family_id' => 2,
                'name' => 'Gato',
                'description' => 'Gato',
                'min_hp' => 1,
                'max_hp' => 10,
                'min_attack' => 1,
                'max_attack' => 10,
                'min_defense' => 1,
                'max_defense' => 10,
                'image_path' => 'uploads/animals/gato.png',
            ],
            [
                'animal_especie_id' => 2,
                'animal_family_id' => 2,
                'name' => 'Simba',
                'description' => 'Gato',
                'min_hp' => 150,
                'max_hp' => 300,
                'min_attack' => 100,
                'max_attack' => 400,
                'min_defense' => 200,
                'max_defense' => 350,
                'image_path' => 'uploads/animals/gato-2.png',
            ],
            [
                'animal_especie_id' => 2,
                'animal_family_id' => 2,
                'name' => 'Milo',
                'description' => 'Gato',
                'min_hp' => 200,
                'max_hp' => 350,
                'min_attack' => 150,
                'max_attack' => 450,
                'min_defense' => 250,
                'max_defense' => 500,
                'image_path' => 'uploads/animals/gato-3.png',
            ],
            [
                'animal_especie_id' => 2,
                'animal_family_id' => 2,
                'name' => 'Luna',
                'description' => 'Gato',
                'min_hp' => 250,
                'max_hp' => 400,
                'min_attack' => 200,
                'max_attack' => 500,
                'min_defense' => 300,
                'max_defense' => 550,
                'image_path' => 'uploads/animals/gato-4.png',
            ],
            [
                'animal_especie_id' => 2,
                'animal_family_id' => 2,
                'name' => 'Oliver',
                'description' => 'Gato',
                'min_hp' => 300,
                'max_hp' => 450,
                'min_attack' => 250,
                'max_attack' => 550,
                'min_defense' => 350,
                'max_defense' => 600,
                'image_path' => 'uploads/animals/gato-2.png',
            ],
            [
                'animal_especie_id' => 2,
                'animal_family_id' => 2,
                'name' => 'Bella',
                'description' => 'Gato',
                'min_hp' => 350,
                'max_hp' => 500,
                'min_attack' => 300,
                'max_attack' => 600,
                'min_defense' => 400,
                'max_defense' => 650,
                'image_path' => 'uploads/animals/gato-3.png',
            ],
            [
                'animal_especie_id' => 2,
                'animal_family_id' => 2,
                'name' => 'Leo',
                'description' => 'Gato',
                'min_hp' => 400,
                'max_hp' => 550,
                'min_attack' => 350,
                'max_attack' => 650,
                'min_defense' => 450,
                'max_defense' => 700,
                'image_path' => 'uploads/animals/gato-4.png',
            ],
            [
                'animal_especie_id' => 2,
                'animal_family_id' => 2,
                'name' => 'Chloe',
                'description' => 'Gato',
                'min_hp' => 450,
                'max_hp' => 600,
                'min_attack' => 400,
                'max_attack' => 700,
                'min_defense' => 500,
                'max_defense' => 750,
                'image_path' => 'uploads/animals/gato.png',
            ],
            [
                'animal_especie_id' => 2,
                'animal_family_id' => 2,
                'name' => 'Charlie',
                'description' => 'Gato',
                'min_hp' => 500,
                'max_hp' => 650,
                'min_attack' => 450,
                'max_attack' => 750,
                'min_defense' => 550,
                'max_defense' => 600,
                'image_path' => 'uploads/animals/gato-2.png',
            ],
            [
                'animal_especie_id' => 2,
                'animal_family_id' => 2,
                'name' => 'Lucy',
                'description' => 'Gato',
                'min_hp' => 550,
                'max_hp' => 700,
                'min_attack' => 500,
                'max_attack' => 650,
                'min_defense' => 600,
                'max_defense' => 650,
                'image_path' => 'uploads/animals/gato-3.png',
            ],
            [
                'animal_especie_id' => 3,
                'animal_family_id' => 3,
                'name' => 'Thunder',
                'description' => 'Cavalo',
                'min_hp' => 1500,
                'max_hp' => 1800,
                'min_attack' => 1200,
                'max_attack' => 1900,
                'min_defense' => 1100,
                'max_defense' => 1700,
                'image_path' => 'uploads/animals/cavalo.png',
            ],
            [
                'animal_especie_id' => 3,
                'animal_family_id' => 3,
                'name' => 'Spirit',
                'description' => 'Cavalo',
                'min_hp' => 1000,
                'max_hp' => 1500,
                'min_attack' => 1300,
                'max_attack' => 1700,
                'min_defense' => 1150,
                'max_defense' => 1600,
                'image_path' => 'uploads/animals/cavalo-2.png',
            ],
            [
                'animal_especie_id' => 3,
                'animal_family_id' => 3,
                'name' => 'Shadowfax',
                'description' => 'Cavalo',
                'min_hp' => 1400,
                'max_hp' => 2000,
                'min_attack' => 1600,
                'max_attack' => 1900,
                'min_defense' => 1300,
                'max_defense' => 1500,
                'image_path' => 'uploads/animals/cavalo-3.png',
            ],
            [
                'animal_especie_id' => 3,
                'animal_family_id' => 3,
                'name' => 'Bucephalus',
                'description' => 'Cavalo',
                'min_hp' => 1200,
                'max_hp' => 1700,
                'min_attack' => 1500,
                'max_attack' => 1800,
                'min_defense' => 1400,
                'max_defense' => 1600,
                'image_path' => 'uploads/animals/cavalo-4.png',
            ],
            [
                'animal_especie_id' => 3,
                'animal_family_id' => 3,
                'name' => 'Silver',
                'description' => 'Cavalo',
                'min_hp' => 1600,
                'max_hp' => 1900,
                'min_attack' => 1700,
                'max_attack' => 2000,
                'min_defense' => 1200,
                'max_defense' => 1400,
                'image_path' => 'uploads/animals/cavalo.png',
            ],
            [
                'animal_especie_id' => 3,
                'animal_family_id' => 3,
                'name' => 'Seabiscuit',
                'description' => 'Cavalo',
                'min_hp' => 1100,
                'max_hp' => 1300,
                'min_attack' => 1400,
                'max_attack' => 1700,
                'min_defense' => 1500,
                'max_defense' => 1900,
                'image_path' => 'uploads/animals/cavalo-2.png',
            ],
            [
                'animal_especie_id' => 3,
                'animal_family_id' => 3,
                'name' => 'Rocinante',
                'description' => 'Cavalo',
                'min_hp' => 1800,
                'max_hp' => 2000,
                'min_attack' => 1600,
                'max_attack' => 1900,
                'min_defense' => 1300,
                'max_defense' => 1700,
                'image_path' => 'uploads/animals/cavalo-3.png',
            ],
            [
                'animal_especie_id' => 3,
                'animal_family_id' => 3,
                'name' => 'Pegasus',
                'description' => 'Cavalo',
                'min_hp' => 1700,
                'max_hp' => 1900,
                'min_attack' => 1500,
                'max_attack' => 2000,
                'min_defense' => 1200,
                'max_defense' => 1600,
                'image_path' => 'uploads/animals/cavalo-4.png',
            ],
            [
                'animal_especie_id' => 3,
                'animal_family_id' => 3,
                'name' => 'Epona',
                'description' => 'Cavalo',
                'min_hp' => 1400,
                'max_hp' => 1800,
                'min_attack' => 1100,
                'max_attack' => 1600,
                'min_defense' => 1300,
                'max_defense' => 1700,
                'image_path' => "uploads/animals/cavalo.png",
            ],
        ];
    }
}
